spring:
  ai:
    model:
      chat: openai
    openai:
      base-url: https://i.alal.site/v1beta/openai
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gemini-2.5-flash
        completions-path: /chat/completions
  application:
    name: GTool
  thymeleaf:
    cache: true
server:
  port: 5010
#log config
logging:
  level:
    com.way: info
    root: info
  file:
    name: ./logs/gtool.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-file-size: 120MB
      # max-history: 30
      total-size-cap: 3GB
gtool:
  host: http://localhost:5010